stages:
  - build
  - test
  - coverage

build-code:
  image: eslib/debian-gcc:12.2.0
  stage: build
  script:
    - cmake -S. -Bbuild
    - cmake --build build

test-code:
  image: eslib/debian-gcc:12.2.0
  stage: build
  script:
    - cmake -S. -Bbuild
    - cmake --build build
    - cmake --build build -t test

cover-code:
  image: eslib/debian-gcc:12.2.0
  stage: coverage
  script:
    - cmake -S. -Bbuild_cov -DDO_COVERAGE=On
    - cmake --build build_cov
    - cmake --build build_cov -t coverage
  coverage: '/Total:\|(\d+\.?\d+\%)/'
