stages:
  - build
  - test

build-code:
  image: eslib/debian-gcc:12.2.0
  stage: build
  script:
    - cmake -S. -Bbuild
    - cmake --build build

test-code:
  image: eslib/debian-gcc:12.2.0
  stage: build
  script:
    - ctest --test-dir build
